---
title: "Demo"
output: html_document
---
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```
## Fractal by R

### Declare value
```{r}
n0 = matrix( c( 0, 0, 0, 0.16), nrow=2, ncol=2, byrow = TRUE )
n1 = matrix( c( 0.85, 0.04, -0.04, 0.85), nrow=2, ncol=2, byrow = TRUE )
n2 = matrix( c( 0.2, -0.26, 0.23, 0.22), nrow=2, ncol=2, byrow = TRUE )
n3 = matrix( c( -0.15, 0.28, 0.26, 0.24), nrow=2, ncol=2, byrow = TRUE )
p = matrix( c(0,0), nrow=2, ncol=1, byrow = TRUE)

xais = 2
yais = 40000
vectorShow = matrix (nrow = yais, ncol = xais )

probab = seq(1,40000)
probab = runif(40000, 0, 1)
```

### For loop, 40000 point
```{r}

for (i in 1:40000){
  if (probab[i]*100 <= 5 & probab[i]*100 > 0) {
    p = n0 %*% p
    vectorShow[i,] = p[,1]
  } else if (probab[i]*100 > 5 & probab[i]*100 <= 86){
    p = n1 %*% p + matrix( c(0, 1.6), nrow=2, ncol=1, byrow = TRUE)
    vectorShow[i,] = p[,1]
  } else if(probab[i]*100 > 86 & probab[i]*100 <= 93){
    p = n2 %*% p + matrix( c(0, 1.6), nrow=2, ncol=1, byrow = TRUE)
    vectorShow[i,] = p[,1]
  } else if (probab[i]*100 > 93 & probab[i]*100 <= 100) {
    p = n3 %*% p + matrix( c(0, 0.44), nrow=2, ncol=1, byrow = TRUE)
    vectorShow[i,] = p[,1]
  }
}
```

### Show the result of Fractal
```{r, echo=FALSE}
plot(x = vectorShow[, 2], y = vectorShow[, 1], plt = c(0, 10, -5, 5), cex = 0.1, asp = 1, col="#5FB404" )
```


